import React from 'react';
import './Legal.css';

const Terms = () => {
    return (
        <div className="legal-page container">
            <h1>Terms of Service</h1>
            <p className="last-updated">Last Updated: January 1, 2024</p>

            <section>
                <h2>1. Acceptance of Terms</h2>
                <p>By accessing PrivacyRisk.io, you verify that you have read and agree to these terms.</p>
            </section>

            <section>
                <h2>2. Disclaimer</h2>
                <p>The risk scores provided are for informational purposes only. They are generated by automated heuristic algorithms and should not be considered legal or professional security advice.</p>
            </section>

            <section>
                <h2>3. Usage Limits</h2>
                <p>We maintain the right to rate-limit or block IP addresses that abuse our scanning API.</p>
            </section>
        </div>
    );
};

export default Terms;
